import type { Metadata } from "next";
import { requirePagePermission } from "@/lib/auth/guards";
import { AdminPageHeader } from "@/components/admin/admin-page-header";
import { EmptyState } from "@/components/ui/empty-state";
import { auditRepository, userRepository } from "@/lib/repositories";

export const metadata: Metadata = { title: "Audit Log" };

export default async function AdminAuditLogPage() {
  await requirePagePermission("auditlog.view");
  const [entries, users] = await Promise.all([auditRepository.list(100), userRepository.listAll()]);
  const userNameById = new Map(users.map((u) => [u.id, u.name]));

  return (
    <div>
      <AdminPageHeader
        title="Audit Log"
        description="Security-relevant events for this server session (logins, role changes, publish attempts)."
      />

      <div className="mb-6 rounded-xl border border-dashed border-ink/20 bg-ink/[0.02] px-5 py-3 text-xs text-ink/60">
        These entries are real and generated by actual actions in this
        environment (e.g. sign in with the bootstrap admin, then reload this
        page). They are kept in memory and reset when the server restarts —
        connect the database to persist them via the{" "}
        <code className="rounded bg-ink/5 px-1">AuditLog</code> model.
      </div>

      {entries.length === 0 ? (
        <EmptyState
          title="No activity recorded yet"
          description="Sign in, sign out, or attempt a content action to generate entries here."
        />
      ) : (
        <div className="overflow-x-auto rounded-xl border border-ink/10 bg-white/40">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-ink/10 text-xs uppercase tracking-wide text-ink/50">
              <tr>
                <th className="px-4 py-3">When</th>
                <th className="px-4 py-3">Who</th>
                <th className="px-4 py-3">Action</th>
                <th className="px-4 py-3">Target</th>
                <th className="px-4 py-3">Result</th>
              </tr>
            </thead>
            <tbody>
              {entries.map((entry) => (
                <tr key={entry.id} className="border-b border-ink/5 last:border-0">
                  <td className="px-4 py-3 text-ink/50">
                    {entry.createdAt.toLocaleString("en-UG")}
                  </td>
                  <td className="px-4 py-3">
                    {entry.userId ? (userNameById.get(entry.userId) ?? entry.userId) : "—"}
                  </td>
                  <td className="px-4 py-3 font-mono text-xs">{entry.action}</td>
                  <td className="px-4 py-3 text-ink/70">{entry.resource}</td>
                  <td className="px-4 py-3">
                    <span
                      className={`rounded-full px-2 py-0.5 text-xs font-semibold ${
                        entry.result === "success"
                          ? "bg-forest/10 text-forest"
                          : "bg-red-50 text-red-800"
                      }`}
                    >
                      {entry.result}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
